### ISSUE TITLE
Failed Paypal Test results in endless redirect

### ISSUE THREAD

**Issue by mihob** [craftcms/commerce-stripe#266] opened 2023-11-16 15:55 UTC
### Description

If you allow a PayPal payment to fail in Stripe's test mode, the process results in an endless redirect

![image](https://github.com/craftcms/commerce-stripe/assets/48485580/728efbed-1688-433b-9ffc-a8b2b7e0ee1c)

### Steps to reproduce

1. Select PayPal as the payment method
2. Select "FAIL TEST PAYMENT" on the Stripe test page

### Additional info

- Craft CMS version: Craft Pro 4.5.10
- Stripe for Craft Commerce version: 4.0.1.1
- PHP version: 8.2.12
- Database driver & version: MariaDB 11.1.2
- Plugins & versions:

  - Asset Locations	2.2.1
  - BlurHash	2.0.5
  - Control Panel CSS	2.6.0
  - CP Clear Cache	1.3.0
  - CP Field Inspect	1.4.4
  - Craft Commerce	4.3.2
  - Default Dashboard	2.0.1
  - Easy Image	1.0.1
  - Events	2.0.2
  - Expanded Singles	2.0.5
  - Field Manager	3.0.8
  - Matrix Colors	3.0.0
  - MatrixMate	2.1.4
  - PayPal Checkout for Craft Commerce	2.1.2
  - Redactor	3.0.4
  - Schedule	0.4.0.1
  - Sentry Logger	4.1.3
  - SEOMate	2.1.2
  - Smith	2.0.0
  - Stripe for Craft Commerce	4.0.1.1
  - Super Table	3.0.12
  - Typed link field	2.1.5
  - Vite	4.0.6

**Comment by mihob** [comment] 2023-11-20 10:14
Any news on this?

**Comment by steverowling** [comment] 2023-11-28 16:54
I've also experienced this.

**Comment by mihob** [comment] 2023-12-18 10:49
@nfourtythree Any news on this issues?

**Comment by mihob** [comment] 2023-12-19 09:27
@nfourtythree The problem also occurs live.

To be honest, I'm a little disappointed. Craft Commerce is quite expensive and I would expect a first party plugin to one of the major payment providers to work correctly. Or that there is at least some kind of reliable support.

The problem has been open for over a month now without the slightest feedback.

**Comment by nfourtythree** [comment] 2023-12-19 09:39
Hi All

Thank you for reporting, we have replicated the issue for this and will look into the causes.

Please follow along with this issue for any further updates.

Thanks!

**Comment by nfourtythree** [comment] 2023-12-19 14:01
Hi All

We have pushed up a fix for this that has been included in the latest release of the plugin `4.1.0`.

This version is now available.

Thanks!

**Closed by nfourtythree** 2023-12-19 14:01 UTC
Labels: bug
