### ISSUE TITLE
cannot update plugin

### ISSUE THREAD

**Issue by paulmendrik** [craftcms/commerce-stripe#255] opened 2023-10-06 08:57 UTC
### Description
When trying to update the plug into the latest version I get the following :  
Problem 1
    - craftcms/commerce-stripe 4.0.1 requires stripe/stripe-php ^10.0 -> found stripe/stripe-php[v10.0.0, ..., v10.21.0] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires craftcms/commerce-stripe 4.0.1 -> satisfiable by craftcms/commerce-stripe[4.0.1].

### Steps to reproduce

1.
2.

### Additional info

- Craft CMS version: 4.3.3
- Stripe for Craft Commerce version: 3.1.1
- PHP version:8.2.4
- Database driver & version:MySQL 8.0.34
- Plugins & versions:
- Craft Commerce | 4.3.0
- ImageOptimize | 4.0.5
- Redactor | 3.0.4
- Store Hours | 3.0.0
- Stripe for Craft Commerce | 3.1.1
- Super Table | 3.0.12
- Stripe Payments 5.3.1 (not installed because of conflict)
-- | --

**Comment by lukeholder** [comment] 2023-10-06 10:06
Looks like you are requiring the stripe php packing in your root project which is conflicting?

**Comment by paulmendrik** [comment] 2023-10-06 11:13
Thanks Luke it's probably conflicting with Stripe Payments from Enupal which I had installed but disabled and then unistalled. At least that's when the problems started . If I enable or reinstall it I have to disable / uninstall Stripe for Craft or that one won't install and if I do that the payment gateway won' work. At least not having Stripe Payments installed the payment gateway is working correctly even if I cannot update Stripe for Craft to it's latest version.

**Comment by lukeholder** [comment] 2024-03-08 03:42
Duplicate of https://github.com/craftcms/commerce-stripe/issues/287

**Closed by lukeholder** 2024-03-08 03:42 UTC
Labels: bug
