### ISSUE TITLE
Issue with AWS3 Plugin on installing

### ISSUE THREAD

**Issue by NixonGit** [craftcms/commerce-stripe#142] opened 2021-01-13 10:44 UTC
### Description
Tried to install via plugin store and via command line, same result. Issue with AWS plugin that is already installed

 Problem 1
    - The requested package craftcms/aws-s3 (locked at 1.2.8, required as 1.2.11) is satisfiable by craftcms/aws-s3[1.2.8] but these conflict with your requirements or minimum-stability.
 Problem 2
    - Installation request for craftcms/aws-s3 1.2.11 -> satisfiable by craftcms/aws-s3[1.2.11].
    - Conclusion: remove league/flysystem-aws-s3-v3 1.0.25
    - Conclusion: don't install league/flysystem-aws-s3-v3 1.0.25
    - craftcms/aws-s3 1.2.11 requires league/flysystem-aws-s3-v3 ^1.0.28 -> satisfiable by league/flysystem-aws-s3-v3[1.0.28, 1.0.29].
    - Can only install one of: league/flysystem-aws-s3-v3[1.0.28, 1.0.25].
    - Can only install one of: league/flysystem-aws-s3-v3[1.0.29, 1.0.25].
    - Installation request for league/flysystem-aws-s3-v3 (locked at 1.0.25) -> satisfiable by league/flysystem-aws-s3-v3[1.0.25].

### Additional info

- Craft version: Craft Pro 3.4.28.1
- PHP version: 7.3.9
- Database driver & version: MySQL 5.7.26
- Plugins & versions: Amazon S3 | 1.2.8, Commerce 3.1.12

**Comment by angrybrad** [comment] 2021-01-13 19:43
Closing as a dupe of https://github.com/craftcms/commerce-stripe/issues/143

**Closed by angrybrad** 2021-01-13 19:43 UTC
Labels: bug
