### ISSUE TITLE
Stripe Checkout Doesn't Work

### ISSUE THREAD

**Issue by bryantwells** [craftcms/commerce-stripe#261] opened 2023-11-04 21:56 UTC
### Description

Stripe Checkout does not work as outlined in the docs. It seems Craft requires a relative path for a Cancel URL, which is incompatible with Stripe's requirement of an HTTPS Cancel URL.

#### Scenario 1
Results in Stripe error: "Not a Valid URL"
```
<form method="POST">
    {{ csrfInput() }}
    {{ actionInput('commerce/payments/pay') }}
    {{ hiddenInput('gatewayId', gateway.id) }}

    {# Cancel URL #}
    {{ hiddenInput('cancelUrl', 'checkout' | hash) }}

    {% namespace gateway.handle|commercePaymentFormNamespace %}
        {{ gateway.getPaymentFormHtml({})|raw }}
    {% endnamespace %}
</form>
```

#### Scenario 2
Results in Craft error: "Request contained an invalid body param"
```
<form method="POST">
    {{ csrfInput() }}
    {{ actionInput('commerce/payments/pay') }}
    {{ hiddenInput('gatewayId', gateway.id) }}

    {# Cancel URL #}
    {{ hiddenInput('cancelUrl', currentSite.baseUrl ~ '/checkout'|hash) }}

    {% namespace gateway.handle|commercePaymentFormNamespace %}
        {{ gateway.getPaymentFormHtml({})|raw }}
    {% endnamespace %}
</form>
```

### Fix?
I was only able to get this to work by changing line 537 in `PaymentIntents.php`:
```
// 'cancel_url' =>  $transaction->getOrder()->cancelUrl,
'cancel_url' => Craft::$app->getSites()->getCurrentSite()->baseUrl . $transaction->getOrder()->cancelUrl,
```

### Additional info

- Craft CMS version: 4.5.9
- Stripe for Craft Commerce version: 4.0.1.1
- PHP version: 8.0.2.8
- Database driver & version: MariaDB 10.4.28
- Plugins & versions: Craft Commerce 4.3.1

**Comment by bryantwells** [comment] 2023-11-05 20:59
For anyone having a similar issue and looking for a cleaner fix, I was able to get this working by creating a new module and tying into the `buildGatewayRequest` event 

```
use craft\commerce\models\Transaction;
use craft\commerce\stripe\events\BuildGatewayRequestEvent;
use craft\commerce\stripe\gateways\PaymentIntents;
use yii\base\Event;
use craft\helpers\UrlHelper;

Event::on(
    PaymentIntents::class,
    PaymentIntents::EVENT_BUILD_GATEWAY_REQUEST,
    function(BuildGatewayRequestEvent $e) {
        /** @var Transaction $transaction */
        $transaction = $e->transaction;
        $order = $transaction->getOrder();
        
        $e->request['cancel_url'] = UrlHelper::baseUrl() . $order->cancelUrl;
    }
);
```

**Comment by pixelmachine** [comment] 2023-11-15 15:00
@bryantwells I think the issue is the formatting of your URL and hash.

You're using:
```twig
{{ hiddenInput('cancelUrl', currentSite.baseUrl ~ '/checkout'|hash) }}
```
Which gives an output of:
```html
<input type="hidden" name="cancelUrl" value="https://yoursite.com/[hash]/checkout">
```

Instead you need to format your URL so that the hash is added in the right place, for example:
```twig
{{ hiddenInput('cancelUrl', siteUrl('/checkout')|hash) }}  {# url() might also work #}
```
That should give you an output like:
```html
<input type="hidden" name="cancelUrl" value="[hash]https://yoursite.com/checkout">
```

At least I can confirm this is working correctly for me.

**Comment by lukeholder** [comment] 2024-03-08 03:30
Closed as confirmed the hashing of the URL was not done on the whole value. Thanks @pixelmachine

**Closed by lukeholder** 2024-03-08 03:30 UTC
Labels: bug
