### ISSUE TITLE
Stripe client secret?

### ISSUE THREAD

**Issue by gregorterrill** [craftcms/commerce-stripe#223] opened 2022-11-15 19:46 UTC
### Description
Running into a similar issue as #214 although it's not clear how that was solved.

I can't get my customized payment form working without providing a client secret to `stripe.elements()` - I'm using the [Appearance API](https://stripe.com/docs/elements/appearance-api) to modify the form, so I need to call it like this:

`const elements = stripe.elements({clientSecret, appearance});`

If I pass a totally bogus value as clientSecret, the Elements JS fails to run and the form doesn't get initalized. If I pass a value in the correct format `pi_blah_secret_blah` then the JS runs but I see in the console a 400 to https://api.stripe.com/v1/elements/sessions and a 404 to https://api.stripe.com/v1/payment_intents however it seems like the payment still goes through. If I pass in _any_ client secret from any past PaymentIntent made through the example Commerce templates (which can be found digging through the intentData in the stripe_paymentintents DB table) it works with no 400 errors, although that's clearly not what I should be doing. Not sure how using a client secret for a different transaction would impact things - it hasn't caused any strange behaviour yet in testing though (maybe if my Stripe account were in live mode this would break things, I dunno).

Not sure that this is necessarily a bug or just a documentation issue, but in any case, are you able to provide an example of the correct way to get either the client secret, Stripe reference number, or PaymentIntent for the current cart and/or the current subscription plan? If I had the ref I could get the client secret as below (in a custom module). However, I'm not sure if its possible to get the ref value for the current cart/subscription transaction prior to any payment being sent to Stripe (as the payment form hasn't even been initialized yet).

```
$ref = 'pi_XXXXXXXXXXXXXXXXX';
$intent = StripePlugin::getInstance()->getPaymentIntents()->getPaymentIntentByReference($ref);
$intentData = json_decode($intent->intentData);
$clientSecret = $intentData->client_secret;
```

### Additional info

- Craft CMS version: 4.3.1
- Stripe for Craft Commerce version: 3.0.1
- PHP version: 8.1.5

**Comment by gaelpleeroy** [comment] 2023-01-24 14:43
I do have the same issue as I would like to use the Stripe Elements but without the client secret it's not possible.

**Comment by nicholasc** [comment] 2023-01-31 21:18
Having the same issue here. @gregorterrill did you happen to make it work in production?

**Comment by pdaleramirez** [comment] 2023-02-02 06:38
@gregorterrill Would it be possible to attach the Secret Keys in the container form? and then call the value in JavaScript?  Similar to how the stripe intentsForm.twig does it here https://github.com/craftcms/commerce-stripe/blob/e7cd3cb240a2e85ccacb335a77a4d5bef76e0ee3/src/templates/paymentForms/intentsForm.twig#L5

**Comment by westhouseit** [comment] 2023-02-10 16:18
@pdaleramirez That only works because the clientSecret template variable is declared here:
https://github.com/craftcms/commerce-stripe/blob/62e04b0a8a640a238e8f8b86141b4b6b6a426fcd/src/gateways/PaymentIntents.php#L387

**Comment by westhouseit** [comment] 2023-02-10 16:20
As far as I can see it's currently impossible to use the Payment Element (https://stripe.com/docs/payments/payment-element).

Please can you re-add the bug tag.

**Comment by samueldraper** [comment] 2023-02-12 08:47
@pdaleramirez @lukeholder we are having this issue and it's now critical for it to be fixed. Please could you re-categorise this as a bug and prioritise so that we can Stripe's Payment Element as intended. Thank you.

**Comment by gregorterrill** [comment] 2023-02-12 13:30
@pdaleramirez That doesn't work because the PaymentIntent hasn't been created yet (in the majority of cases for my checkout flow, at least), and therefore there's no client secret yet. The only "solution" I've found is to bypass commerce-stripe entirely and create my own API endpoint which gets a client secret per the instructions from [Stripe's documentation](https://stripe.com/docs/payments/quickstart).

In the Twig template JS, this is how I'm initializing the card field using the Stripe Elements API:

```
const stripe = Stripe("{{ getenv('STRIPE_PUBLISHABLE_API_KEY') }}");
const appearance = {
  theme: 'none',
};
const style = {
  base: {
    color: '#3B3B3B',
    backgroundColor: 'transparent',
    fontFamily: '"Public Sans", "Avenir Next Condensed", "Arial Narrow", sans-serif',
    fontSmoothing: 'antialiased',
    fontSize: '16px',
    '::placeholder': {
      color: '#706B67'
    }
  },
  invalid: {
    color: '#F80000',
    iconColor: '#F80000'
  }
};

let elements;
let card;
const form = document.getElementById('payment-form');

initializeStripeElements();

async function initializeStripeElements() {
    const { clientSecret } = await fetch("{{ siteUrl('actions/dashboard/get-new-stripe-client-secret') }}", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ 
        {{ craft.app.config.general.csrfTokenName|e('js') }} : "{{ craft.app.request.csrfToken|e('js') }}",
        amount: {{ max(cart ? cart.totalPrice, 1) * 100}}, // Stripe wants this value in cents, and has a $1 minimum
        userId: {{ currentUser.id }},
        gatewayId: {{ gatewayId }}
      }),
    }).then((r) => r.json());

    // This is the line causing the error if we don't do the above call because it fails without a clientSecret
    elements = stripe.elements({ clientSecret, appearance }); 

    card = elements.create('card', { style: style });
    card.mount('#card-element');

    card.on('change', function({error}) {
      let displayError = document.getElementById('card-errors');
      if (error) {
        displayError.textContent = error.message;
      } else {
        displayError.textContent = '';
      }
    });
  }
```

And the API endpoint:

```
public function actionGetNewStripeClientSecret(): ?Response 
    {
      // Commerce Stripe doesn't currently support getting client secrets for fresh transactions, so we do this manually
      // per the instructions here: https://stripe.com/docs/payments/quickstart
      $this->requirePostRequest();
      $amount = $this->request->getParam('amount');
      $userId = $this->request->getParam('userId');
      $gatewayId = $this->request->getParam('gatewayId');

      // get customer as we need to pass the Stripe customer ref ID
      $customer = StripePlugin::getInstance()->customers->getCustomerById($userId);

      // make sure the user has a payment source
      $userPaymentSources = Commerce::getInstance()->getPaymentSources()->getAllPaymentSourcesByCustomerId($userId);
      if (isset($userPaymentSources[0])) {
        $paymentSource = $userPaymentSources[0];
      }

      \Stripe\Stripe::setApiKey(App::env('STRIPE_SECRET_API_KEY'));

      $paymentIntent = \Stripe\PaymentIntent::create([
        'amount' => $amount,
        'currency' => 'cad',
        'customer' => $customer->reference ?? null,
        'payment_method' => $paymentSource ?? null
      ]);

      $response = array(
        'clientSecret' => $paymentIntent->client_secret
      );

      return $this->asJson($response);
    }
```

I could be way off base here, but this seems to work, in that I can finally initialize card elements, but it is not without it's own problems - what ends up happening is every time someone hits a payment screen (or just wants to edit a saved card which also needs its fields initialized this way), it creates a $1 PaymentIntent which shows up as an incomplete payment in Stripe (because if they proceed with the purchase, Craft creates its own PaymentIntent and uses that). Also it seems like commerce-stripe should be able to handle this functionality instead of having to go directly via the Stripe API.

**Comment by pdaleramirez** [comment] 2023-03-02 06:20
@gregorterrill There will be a completely new Stripe gateway plugin that supports Stripe elements. We’ll be releasing it soon. We’ll update this issue when it gets released.

**Comment by gregorterrill** [comment] 2023-03-02 14:17
@pdaleramirez That's good news! Will the new version also support subscriptions?

**Comment by westhouseit** [comment] 2023-03-06 11:13
@pdaleramirez So that we can plan, do you have an approximate timescale for completion - days, weeks, months?

**Comment by westhouseit** [comment] 2023-03-25 12:25
@pdaleramirez Can we please have an update/timeline.

**Comment by samueldraper** [comment] 2023-03-28 15:49
@pdaleramirez Please can you give us an ETA on the new plugin.

**Comment by samueldraper** [comment] 2023-05-22 20:17
> @pdaleramirez Please can you give us an ETA on the new plugin.

@pdaleramirez on 30th March the code was being finalised and would be released within a few weeks. Are you able to give an updated release date please?

**Comment by lukeholder** [comment] 2023-06-01 13:11
Hi guys, I will be posting instructions for testing the Beta of the new Stripe plugin with Stripe elements support here next week. Stay tuned. Thanks!

**Comment by samueldraper** [comment] 2023-09-06 13:17
Any update please @lukeholder ?

**Comment by lukeholder** [comment] 2023-09-14 02:55
Good news! See our announcement:

 https://craftcms.com/blog/commerce-4-3-stripe-4

**Closed by lukeholder** 2023-09-14 02:55 UTC
Labels: question

**Comment by samueldraper** [comment] 2023-09-14 07:07
Superb. Thank you. On 14 Sep 2023, at 03:56, Luke Holder ***@***.***> wrote:﻿
Good news! See our announcement:
https://craftcms.com/blog/commerce-4-3-stripe-4
